/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Controller;
import java.awt.Image;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author Olivier
 */
public class GeneralPanel extends ApplicationPanel
{
    private JPanel currentPanel;
    
    /**
     * Creates new form GeneralPanel
     */
    public GeneralPanel()
    {
        currentPanel = null;
        initComponents();
        btnVerrouillage.setToolTipText("Déconnexion");
        btnRetour.setToolTipText("Retour vers fenêtre " + previousPanelTitle);
        

        try
        {
            Image img = ImageIO.read(getClass().getResource("../images/cadenas.png"));
            btnVerrouillage.setIcon(new ImageIcon(img));
        } 
        catch (IOException ex)
        {
            //System.out.println(ex.getMessage());
        }
    }
    
    /**
     * 
     * @param newControleur 
     */
    public void setListener(Controller newControleur)
    {
        this.controleur = newControleur;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel1 = new javax.swing.JLabel();
        btnRetour = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnVerrouillage = new javax.swing.JButton();
        serveurConnecte = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("jLabel1");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnRetour.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnRetour.setText("<< Retour");
        btnRetour.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRetour.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnRetourActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("jLabel2");

        btnVerrouillage.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVerrouillage.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnVerrouillageActionPerformed(evt);
            }
        });

        serveurConnecte.setText("Serveur/serveuse connecté(e) : ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRetour, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                        .addGap(257, 257, 257)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 516, Short.MAX_VALUE)
                        .addGap(50, 50, 50)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnVerrouillage, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(serveurConnecte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRetour, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(9, 9, 9)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(serveurConnecte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnVerrouillage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(47, 47, 47))))
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * 
     * @param evt 
     */
    private void btnRetourActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnRetourActionPerformed
    {//GEN-HEADEREND:event_btnRetourActionPerformed
        
        controleur.retour(currentPanel);
    }//GEN-LAST:event_btnRetourActionPerformed

    /**
     * 
     * @param evt 
     */
    private void btnVerrouillageActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnVerrouillageActionPerformed
    {//GEN-HEADEREND:event_btnVerrouillageActionPerformed
        
        controleur.deconnexion(currentPanel);
    }//GEN-LAST:event_btnVerrouillageActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRetour;
    private javax.swing.JButton btnVerrouillage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel serveurConnecte;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the jButton1
     */
    public javax.swing.JButton getBtnRetour()
    {
        return btnRetour;
    }

    /**
     * @param jButton1 the jButton1 to set
     */
    public void setjButton1(javax.swing.JButton jButton1)
    {
        this.btnRetour = jButton1;
    }

    /**
     * @return the jLabel1
     */
    public javax.swing.JLabel getjLabel1()
    {
        return jLabel1;
    }
    
    /**
     * 
     * @param name 
     */
    public void changeFrameName(String name)
    {
        this.getjLabel1().setText(name);
    }
    
    /**
     * @param jLabel1 the jLabel1 to set
     */
    public void setjLabel1(javax.swing.JLabel jLabel1)
    {
        this.jLabel1 = jLabel1;
    }

    /**
     * @return the jLabel2
     */
    public javax.swing.JLabel getjLabel2()
    {
        return jLabel2;
    }

    /**
     * @param jLabel2 the jLabel2 to set
     */
    public void setjLabel2(javax.swing.JLabel jLabel2)
    {
        this.jLabel2 = jLabel2;
    }

    /**
     * @return the btnVerrouillage
     */
    public javax.swing.JButton getBtnVerrouillage()
    {
        return btnVerrouillage;
    }

    /**
     * @param btnVerrouillage the btnVerrouillage to set
     */
    public void setBtnVerrouillage(javax.swing.JButton btnVerrouillage)
    {
        this.btnVerrouillage = btnVerrouillage;
    }

    /**
     * @return the serveurConnecte
     */
    public javax.swing.JLabel getServeurConnecte()
    {
        return serveurConnecte;
    }

    /**
     * @param serveurConnecte the serveurConnecte to set
     */
    public void setServeurConnecte(javax.swing.JLabel serveurConnecte)
    {
        this.serveurConnecte = serveurConnecte;
    }

    /**
     * @return the currentPanel
     */
    public JPanel getCurrentPanel()
    {
        return currentPanel;
    }

    /**
     * @param currentPanel the currentPanel to set
     */
    public void setCurrentPanel(JPanel currentPanel)
    {
        this.currentPanel = currentPanel;
    }
}
