/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import java.awt.Component;
import java.awt.GridLayout;
import java.math.RoundingMode;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.Observable;
import java.util.Observer;
import javax.swing.BorderFactory;

import javax.swing.BoxLayout;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JLabel;

import model.Facture;
import model.Item;

/**
 *
 * @author petar
 */
public class Invoicing extends javax.swing.JPanel implements Observer{

    private MainFrame mainFrame;
    private ArrayList<ClientFacture> factureList;
    
    /**
     * Creates new form Facturation
     */
    public Invoicing(MainFrame mainFrame) {
        this.mainFrame = mainFrame;
        initComponents();
        facturesArea.setLayout(new GridLayout(0,3));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        splitBtn = new javax.swing.JButton();
        moveBtn = new javax.swing.JButton();
        mergeBtn = new javax.swing.JButton();
        payBtn = new javax.swing.JButton();
        closeTableBtn = new javax.swing.JButton();
        addClientBtn = new javax.swing.JButton();
        facturesArea = new javax.swing.JPanel();

        splitBtn.setText("Séparer item");
        splitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                splitBtnActionPerformed(evt);
            }
        });

        moveBtn.setText("Déplacer item");
        moveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveBtnActionPerformed(evt);
            }
        });

        mergeBtn.setText("Fusionner facture");

        payBtn.setText("Règler facture");

        closeTableBtn.setText("Fermer Table");

        addClientBtn.setText("Ajouter client");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(mergeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(splitBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(moveBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(payBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(closeTableBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addClientBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(splitBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(moveBtn)
                .addGap(54, 54, 54)
                .addComponent(mergeBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(payBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(closeTableBtn)
                .addGap(61, 61, 61)
                .addComponent(addClientBtn)
                .addContainerGap(130, Short.MAX_VALUE))
        );

        facturesArea.setLayout(new javax.swing.BoxLayout(facturesArea, javax.swing.BoxLayout.LINE_AXIS));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(facturesArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(facturesArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void splitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_splitBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_splitBtnActionPerformed

    private void moveBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_moveBtnActionPerformed
    {//GEN-HEADEREND:event_moveBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_moveBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addClientBtn;
    private javax.swing.JButton closeTableBtn;
    private javax.swing.JPanel facturesArea;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton mergeBtn;
    private javax.swing.JButton moveBtn;
    private javax.swing.JButton payBtn;
    private javax.swing.JButton splitBtn;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
      
    }
    
    public void updateFacture(ArrayList<Facture> factures)
    {
        facturesArea.removeAll();
        for(Facture facture: factures)
        {
            ClientFacture cf = new ClientFacture(facture);
            facturesArea.add(cf);
        }
    }
    
    private class ClientFacture extends javax.swing.JPanel
    {
        Facture facture;
        public ClientFacture(Facture f) {
            facture = f;
            this.setBorder(BorderFactory.createLineBorder(Color.BLACK));
            initComponents();
            setItems();
        }
        
        private void initComponents() {
            
            BoxLayout layout = new BoxLayout(this, BoxLayout.Y_AXIS);
            setLayout(layout);
        }// </editor-fold>
        
        public void setItems()
        {
            ArrayList<Item> items = facture.getItems();
            
            for(Item it : items)
            {
                add(new FactureItem(it.getNomItem(), it.getQuantite(), it.getPrix()));
            }
            
            addTotal();
            addButton();
        }
        
        private void addTotal()
        {
            //add(new JSeparator(JSeparator.HORIZONTAL));
            FactureItem tps= new FactureItem("TPS", facture.calculTPS());
            tps.setAlignmentX(Component.LEFT_ALIGNMENT);
            FactureItem tvq= new FactureItem("TVQ", facture.calculTVQ());
            tvq.setAlignmentX(Component.LEFT_ALIGNMENT);
            FactureItem tot= new FactureItem("Total", facture.calculMontantTotal());
            tot.setAlignmentX(Component.LEFT_ALIGNMENT);
            
            add(tps);
            add(tvq);
            add(tot);
        }
        
        private void addButton()
        {
            this.add(new JButton("Imprimer"));
        }
        private class FactureItem extends javax.swing.JPanel
        {
            private DecimalFormat df;
            
            public FactureItem(String l, double q, double p)
            {
                df = new DecimalFormat("#.##");
                df.setRoundingMode(RoundingMode.HALF_UP);
                initComponent(l, q, p);
            }
            
            public FactureItem(String l, double p)
            {
                df = new DecimalFormat("#.##");
                df.setRoundingMode(RoundingMode.HALF_UP);
                JLabel label1 = new JLabel(l, JLabel.LEFT);
                JLabel label2 = new JLabel(df.format(p), JLabel.RIGHT);
                
                GroupLayout layout = new GroupLayout(this);
                layout.setAutoCreateGaps(true);
                GroupLayout.SequentialGroup hGroup = layout.createSequentialGroup();
                hGroup.addGroup(layout.createParallelGroup().
                        addComponent(label1).addComponent(label2));
                layout.setHorizontalGroup(hGroup);
                
                GroupLayout.SequentialGroup vGroup = layout.createSequentialGroup();
                vGroup.addGroup(layout.createParallelGroup().addComponent(label1));
                vGroup.addGroup(layout.createParallelGroup().addComponent(label2));
                layout.setVerticalGroup(vGroup);
                
                
                
                
            }
            
            private void initComponent(String l, double q, double p)
            {
                JLabel label1 = new JLabel(l, JLabel.LEFT);
                JLabel label2 = new JLabel(df.format(q), JLabel.RIGHT);
                JLabel label3 = new JLabel(df.format(p), JLabel.RIGHT);
                
                GroupLayout layout = new GroupLayout(this);
                layout.setAutoCreateGaps(true);
                GroupLayout.SequentialGroup hGroup = layout.createSequentialGroup();
                hGroup.addGroup(layout.createParallelGroup().
                        addComponent(label1).addComponent(label2)
                        .addComponent(label3));
                layout.setHorizontalGroup(hGroup);
                
                GroupLayout.SequentialGroup vGroup = layout.createSequentialGroup();
                vGroup.addGroup(layout.createParallelGroup().addComponent(label1));
                vGroup.addGroup(layout.createParallelGroup().addComponent(label2));
                vGroup.addGroup(layout.createParallelGroup().addComponent(label3));
                layout.setVerticalGroup(vGroup);
                
                
            }
        }
    }
}
