/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ButtonOrderOverviewListener;
import controller.ButtonModifyOrderListener;
import java.awt.Font;
import static java.awt.Font.BOLD;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import model.Table;

/**
 *
 * @author Olivier
 */
public class TableOrderList extends javax.swing.JPanel
{

    private MainFrame mainFrame;

    /**
     * Creates new form ListeCommandeTable
     */
    public TableOrderList(MainFrame mainFrame)
    {
        this.mainFrame = mainFrame;
        initComponents();
        
        

        jTable1.getTableHeader().setFont(new Font("Tahoma", BOLD, 24));
        jTable1.setRowHeight(50);
        jTable1.setAutoscrolls(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jScrollPane2.setBorder(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String []
            {
                "Numéro de commande", "Modifier la commande"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1030, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the jPanel1
     */
    public javax.swing.JPanel getjPanel1()
    {
        return jPanel1;
    }

    /**
     * @param jPanel1 the jPanel1 to set
     */
    public void setjPanel1(javax.swing.JPanel jPanel1)
    {
        this.jPanel1 = jPanel1;
    }

    /**
     * @return the jLabel1
     */
    public javax.swing.JLabel getjLabel1()
    {
        return jLabel1;
    }

    /**
     * @param jLabel1 the jLabel1 to set
     */
    public void setjLabel1(javax.swing.JLabel jLabel1)
    {
        this.jLabel1 = jLabel1;
    }
    
    public void remplirTableau(Table t)
    {
        int nbCommande = t.getCommandes().size();
        String title[] =
        {
            "Numéro de commande", "Modifier la commande", "Aperçu commande"
        };
        Object[][] data = new Object[nbCommande][3];
        
        for(int i=0;i<nbCommande;i++)
        {
            JLabel l = new JLabel("Commande " + t.getCommandes().get(i).getNumeroCommande());
            l.setFont(new Font("Tahoma", 2, 24));
            
            JButton btnModifier = new JButton("Modifier");
            btnModifier.setFont(new Font("Tahoma", 2, 24));
            
            JButton btnApercu = new JButton("Aperçu");
            btnModifier.setFont(new Font("Tahoma", 2, 24));
            
            data[i][0] = l.getText();
            data[i][1] = "Modifier";
            data[i][2] = "Aperçu";
        }
        
        JTableModel tm = new JTableModel(data, title);
        jTable1.setModel(tm);
        
        jTable1.getColumn("Modifier la commande").setCellRenderer(new ButtonRenderer());
        ButtonEditor btnEditorModifier = new ButtonEditor(new JCheckBox(), new ButtonModifyOrderListener(mainFrame));
        jTable1.getColumn("Modifier la commande").setCellEditor(btnEditorModifier);
        
        jTable1.getColumn("Aperçu commande").setCellRenderer(new ButtonRenderer());
        ButtonEditor btnEditorApercu = new ButtonEditor(new JCheckBox(), new ButtonOrderOverviewListener(mainFrame));
        jTable1.getColumn("Aperçu commande").setCellEditor(btnEditorApercu);
        
        jTable1.getColumn("Numéro de commande").setCellRenderer(new LabelRenderer());
       
    }

}
