/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ButtonAddOrderListener;
import controller.ButtonChargeListener;
import controller.ButtonOrderListListener;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Font;
import static java.awt.Font.BOLD;
import java.util.Observable;
import java.util.Observer;
import javax.swing.BorderFactory;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import model.Serveur;

/**
 *
 * @author Olivier
 */
public class TableList extends JPanel implements Observer
{

    private MainFrame mainFrame;
    private JTable tableau;

    /**
     * Creates new form TableList
     */
    public TableList(MainFrame mainFrame)
    {
        this.mainFrame = mainFrame;

        initComponents();
        btnOuvrirTable.setToolTipText("Accéder à l'écran d'ouverture d'une nouvelle table");


        jPanel1.setBorder(BorderFactory.createLineBorder(Color.gray));

    }

    public void remplirListeTables(Serveur serveur)
    {
        jPanel1.removeAll();
        int nbTables = serveur.getTables().size();
        jLabel2.setText("Section : " + serveur.getSection().getNomSection());
        String title[] =
        {
            "Numéro tables ouvertes", "Facturer", "Ajouter une commande", "Lister les commandes"
        };
        Object[][] data = new Object[nbTables][4];

        for (int i = 0; i < nbTables; i++)
        {
            int code = serveur.getTables().get(i).getNumeroTable();
            JLabel l = new JLabel("- Table" + code);
            l.setFont(new Font("Times New Roman", 2, 24));

            data[i][0] = l.getText();
            data[i][1] = "$";
            data[i][2] = "+";
            data[i][3] = "Détails";
        }


        tableau = new JTable(new JTableModel(data, title));
        tableau.setRowHeight(50);
        tableau.setAutoscrolls(true);
        tableau.setBorder(BorderFactory.createEmptyBorder());

        tableau.getColumn("Facturer").setCellRenderer(new ButtonRenderer());
        ButtonEditor btnEditorFacturer = new ButtonEditor(new JCheckBox(), new ButtonChargeListener(mainFrame));
        tableau.getColumn("Facturer").setCellEditor(btnEditorFacturer);

        tableau.getColumn("Ajouter une commande").setCellRenderer(new ButtonRenderer());
        ButtonEditor btnEditorAjouterCommande = new ButtonEditor(new JCheckBox(), new ButtonAddOrderListener(mainFrame));
        tableau.getColumn("Ajouter une commande").setCellEditor(btnEditorAjouterCommande);

        tableau.getColumn("Lister les commandes").setCellRenderer(new ButtonRenderer());
        ButtonEditor btnEditorListerCommande = new ButtonEditor(new JCheckBox(), new ButtonOrderListListener(mainFrame));
        tableau.getColumn("Lister les commandes").setCellEditor(btnEditorListerCommande);

        getTableau().setRowHeight(50);
        getTableau().setAutoscrolls(true);
        getTableau().setBorder(BorderFactory.createEmptyBorder());


        getTableau().getColumn("Numéro tables ouvertes").setCellRenderer(new LabelRenderer());

        getTableau().getTableHeader().setFont(new Font("Times New Roman", BOLD, 24));

        jPanel1.setLayout(new BorderLayout());
        jPanel1.add(new JScrollPane(getTableau()), BorderLayout.NORTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnOuvrirTable = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1920, 1080));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel2.setText("jLabel2");

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1866, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 546, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1872, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnOuvrirTable.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnOuvrirTable.setText("Ouvrir une nouvelle table");
        btnOuvrirTable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnOuvrirTable.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnOuvrirTable.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnOuvrirTableActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnOuvrirTable, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btnOuvrirTable, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(1004, 1004, 1004)
                .addComponent(jLabel1)
                .addContainerGap(916, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(732, 732, 732))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(386, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnOuvrirTableActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnOuvrirTableActionPerformed
    {//GEN-HEADEREND:event_btnOuvrirTableActionPerformed
        mainFrame.showCurrentPanel("ouvertureTable", "Ouverture d'une table", "tableListPanel");
        mainFrame.getGeneralPanel().setCurrentPanel(mainFrame.getOuvertureTable());
        mainFrame.getGeneralPanel().setPreviousPanel("tableListPanel");
        mainFrame.getGeneralPanel().setPreviousPanelTitle("Liste de vos tables");
        //mainFrame.getOuvertureTable().getFreeTableComboBox()
    }//GEN-LAST:event_btnOuvrirTableActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOuvrirTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg)
    {
        if (arg instanceof Serveur)
        {
            Serveur serveurConnected = (Serveur) arg;
            mainFrame.getGeneralPanel().getServeurConnecte().setText("Serveur/serveuse connecté(e) : " + serveurConnected.getPrenom() + " " + serveurConnected.getNom());
            remplirListeTables(serveurConnected);

        }
    }

    /**
     * @return the tableau
     */
    public JTable getTableau()
    {
        return tableau;
    }

    /**
     * @param tableau the tableau to set
     */
    public void setTableau(JTable tableau)
    {
        this.tableau = tableau;
    }
}
